# Generated by Django 3.2.18 on 2023-03-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
